### ISSUE TITLE
L7的复合图表在使用当前插件后，移动地图会使得Marker绘制位置出现错误

### ISSUE THREAD

**Issue by bigfacewo** [antvis/L7-Leaflet#3]
问题描述：

L7的复合图表在使用当前插件后，移动地图会导致Marker绘制位置出现错误。

原始例子：https://l7.antv.antgroup.com/zh/examples/point/chart#chart

这是最开始的情况，复合图表显示在欧洲区域，
![image](https://user-images.githubusercontent.com/31603897/225792298-d1d36549-3b80-4950-bef9-ec7475aae820.png)

当我移动地图后，例如我移动地图到中国上方，复合图表居然还能看到，并且随着地图移动，这些图表始终在可视区域内。
![image](https://user-images.githubusercontent.com/31603897/225792413-8629a70b-9553-41cf-99e8-f149f0652e87.png)

复现案例：https://codesandbox.io/s/competent-zhukovsky-p2fxnu?file=/index.js

L7 version: 2.14.5
L7-leaflet version: 0.0.3
leaflet version: 1.9.3
g2 version: 4.2.10

@lzxue 大佬能帮忙看看吗？

**Comment by bigfacewo** [comment]
最后，直接使用leafelt的Marker来将图表加到地图上，不使用L7，问题解决。
案例：https://codesandbox.io/s/pensive-ramanujan-ic0il4?file=/index.js

**Comment by lzxue** [comment]
如果是 Maker dom 渲染的建议的使用 leaflet , webgl 海量数据使用 L7
