### ISSUE TITLE
初始化L7Layer的时候，无法传入对scene的配置

### ISSUE THREAD

**Issue by wch360119203** [antvis/L7-Leaflet#5]
想要传入一些scene的初始化配置，比如logoVisible，preserveDrawingBuffer，但是无法做到。

**Comment by wch360119203** [comment]
想要传入一些scene的初始化配置，比如logoVisible，preserveDrawingBuffer，但是无法做到。

**Comment by lzxue** [comment]
这个应该还好吧。默认透传的

**Comment by wch360119203** [comment]
> 这个应该还好吧。默认透传的

https://github.com/antvis/L7-Leaflet/blob/master/src/lib/util.ts
是写死的，13行,createL7Instance方法
