### ISSUE TITLE
使用GaodeMap时，功能不正常

### ISSUE THREAD

**Issue by gdnwr** [antvis/L7-Leaflet#6]
根据L7官网：import { GaodeMap } from '@antv/l7-maps';

1. use in L7
    use in L7示例代码，初始化Scene时将Map替换成GaodeMap
    效果：只有底图，无其他图层
3. use in Leaflet
    use in Leaflet示例代码，修改L7-Leaflet内部源码，将Map替换成GaodeMap
    效果：地图缩放、移动等操作均不正常

**Comment by lzxue** [comment]
高德和 leaflet没法同时使用
